/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JARED
 */
public class EM extends javax.swing.JFrame {
    
    
   
      ConexionBD con= new ConexionBD();
    Connection cn=con.conexion();

    
    
    
    
    /**
     * Creates new form EM
     */
    public EM() {
        initComponents();
           tabla();
    }
           
    
     void tabla ()
    {
        DefaultTableModel modelo = new DefaultTableModel() ;
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellidos");
        modelo.addColumn("Edad");
        modelo.addColumn("Sexo");
        modelo.addColumn("Estado_civil");
        modelo.addColumn("Area_laboral");
        modelo.addColumn("Recidencia");
        modelo.addColumn("Nacionalidad");
        Tablaa.setModel(modelo);
        
        String sql ="SELECT * FROM empleados";
        String datos [] = new String [9];
          try {
              Statement St =cn.createStatement();
              ResultSet rs= St.executeQuery(sql);
              
              while (rs.next())
              {
                  datos[0]=rs.getString(1);
                  datos[1]=rs.getString(2);
                  datos[2]=rs.getString(3);
                  datos[3]=rs.getString(4);
                  datos[4]=rs.getString(5);
                  datos[5]=rs.getString(6);
                  datos[6]=rs.getString(7);
                  datos[7]=rs.getString(8);
                  datos[8]=rs.getString(9);
                  modelo.addRow(datos); 
              
              }
              Tablaa.setModel(modelo);
              
              
          } catch (SQLException ex) {
              Logger.getLogger(EM.class.getName()).log(Level.SEVERE, null, ex);
          }
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        AREA = new javax.swing.JTextField();
        EDAD = new javax.swing.JTextField();
        Vuel = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NACIO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NOM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SEX = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RECI = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        APE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ESTADO = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablaa = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Empleados");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado civil");

        jLabel1.setText("ID");

        AREA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AREAActionPerformed(evt);
            }
        });

        EDAD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDADActionPerformed(evt);
            }
        });

        Vuel.setText("Volver");
        Vuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VuelActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        NACIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NACIOActionPerformed(evt);
            }
        });

        jLabel3.setText("Apellido");

        NOM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOMActionPerformed(evt);
            }
        });

        jLabel4.setText("Edad");

        SEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEXActionPerformed(evt);
            }
        });

        jLabel7.setText("Area Laboral");

        RECI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECIActionPerformed(evt);
            }
        });

        jLabel8.setText("Recidencia");

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Nacionalidad ");

        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        APE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APEActionPerformed(evt);
            }
        });

        jLabel5.setText("Sexo");

        ESTADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTADOActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Vaciar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Tablaa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tablaa);

        jButton5.setText("Actualizar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(NACIO, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(APE, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel9))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(NOM, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(322, 322, 322)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(800, 800, 800)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(RECI, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6))
            .addGroup(layout.createSequentialGroup()
                .addGap(466, 466, 466)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(ESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(953, 953, 953)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(SEX, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(EDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(630, 630, 630)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel7))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8))
            .addGroup(layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(Vuel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(AREA, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(205, 205, 205)
                        .addComponent(NACIO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(APE, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(NOM, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(RECI, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(ESTADO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(SEX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(EDAD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addComponent(Vuel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(AREA, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(132, 132, 132))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VuelActionPerformed
        Principal Menu = new Principal ();
        Menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VuelActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
        try{
            PreparedStatement pps=(PreparedStatement) cn.prepareStatement("INSERT INTO empleados(ID_Empleados,"
                    + "Nombre,Apellidos,Edad,Sexo,Estado_civil,Area_laboral,Recidencia,Nacionalidad) "
                    + "VALUES(?,?,?,?,?,?,?,?,?)");
            pps.setString(1,ID.getText());
            pps.setString(2,NOM.getText());
            pps.setString(3,APE.getText());
            pps.setString(4,EDAD.getText());
            pps.setString(5,SEX.getText());
            pps.setString(6,ESTADO.getText());
            pps.setString(7,AREA.getText());
            pps.setString(8,RECI.getText());
            pps.setString(9,NACIO.getText());
            
           
            int N= pps.executeUpdate(); 
             tabla();
            if (N>0){
            JOptionPane.showMessageDialog(null,"Registro exitoso");
            }
            else 
            {
                 JOptionPane.showMessageDialog(null,"Error");
            }
            
            cn.close();
        }catch(SQLException ex){
            Logger.getLogger(EM.class.getName()).log(Level.SEVERE,null,ex);
           // TODO
    }//GEN-LAST:event_jButton2ActionPerformed
    }
    
    void limpiar ()
    {
        ID.setText("");
        NOM.setText("");
        APE.setText("");
        EDAD.setText("");
        SEX.setText("");
        ESTADO.setText("");
        AREA.setText("");
        RECI.setText("");
        NACIO.setText("");
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       int fila = Tablaa.getSelectedRow();
       String valor = Tablaa.getValueAt(fila, 0).toString();
        if (fila >=0)
        {
            try {
                PreparedStatement pps= cn.prepareStatement("DELETE FROM Empleados where ID_Empleados='"+valor+"'");
                pps.executeUpdate();
                tabla();
      
            } catch (SQLException ex) {
               Logger.getLogger(EM.class.getName()).log(Level.SEVERE, null, ex);
           }
            
    }//GEN-LAST:event_jButton4ActionPerformed
}
    private void NOMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOMActionPerformed
        NOM.transferFocus();
    }//GEN-LAST:event_NOMActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        ID.transferFocus();
    }//GEN-LAST:event_IDActionPerformed

    private void APEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APEActionPerformed
        APE.transferFocus();
    }//GEN-LAST:event_APEActionPerformed

    private void EDADActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDADActionPerformed
        EDAD.transferFocus();
    }//GEN-LAST:event_EDADActionPerformed

    private void SEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEXActionPerformed
        SEX.transferFocus();
    }//GEN-LAST:event_SEXActionPerformed

    private void ESTADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTADOActionPerformed
        ESTADO.transferFocus();
    }//GEN-LAST:event_ESTADOActionPerformed

    private void AREAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AREAActionPerformed
        AREA.transferFocus();
    }//GEN-LAST:event_AREAActionPerformed

    private void RECIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECIActionPerformed
        RECI.transferFocus();
    }//GEN-LAST:event_RECIActionPerformed

    private void NACIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NACIOActionPerformed
        NACIO.transferFocus();
    }//GEN-LAST:event_NACIOActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       limpiar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int fila = Tablaa.getSelectedRow();
        if (fila >=0)
        {
            ID.setText(Tablaa.getValueAt(fila, 0).toString());
            NOM.setText(Tablaa.getValueAt(fila, 1).toString());
            APE.setText(Tablaa.getValueAt(fila, 2).toString());
            EDAD.setText(Tablaa.getValueAt(fila, 3).toString());
            SEX.setText(Tablaa.getValueAt(fila, 4).toString());
            ESTADO.setText(Tablaa.getValueAt(fila, 5).toString());
            AREA.setText(Tablaa.getValueAt(fila, 6).toString());
            RECI.setText(Tablaa.getValueAt(fila, 7).toString());
            NACIO.setText(Tablaa.getValueAt(fila, 8).toString());
        }
        else 
        {
            JOptionPane.showMessageDialog(null, "fila no seleccionada");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
          try {
              PreparedStatement pps=cn.prepareStatement("UPDATE empleados SET Nombre='"
                      +NOM.getText()+"',Apellidos='"+APE.getText()+"',Edad='"+EDAD.getText()+"',Sexo='"+SEX.getText()+"',Estado_civil='"
                      + ESTADO.getText()+"',Area_laboral='"+AREA.getText()+"',Recidencia='"+RECI.getText()+"',Nacionalidad='"
                      +NACIO.getText()+"' Where ID_Empleados ="+ID.getText());
              pps.executeUpdate();
              JOptionPane.showMessageDialog(null, "Actualizacion exitosa");
              tabla();
          } catch (SQLException ex) {
              Logger.getLogger(EM.class.getName()).log(Level.SEVERE, null, ex);
          }

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
     //</editor-fold>
     
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new EM().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField APE;
    private javax.swing.JTextField AREA;
    private javax.swing.JTextField EDAD;
    private javax.swing.JTextField ESTADO;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField NACIO;
    private javax.swing.JTextField NOM;
    private javax.swing.JTextField RECI;
    private javax.swing.JTextField SEX;
    private javax.swing.JTable Tablaa;
    private javax.swing.JButton Vuel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
