/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sql;

/**
 *
 * @author JARED
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        EM = new javax.swing.JMenuItem();
        Producto = new javax.swing.JMenu();
        Lap = new javax.swing.JMenuItem();
        Des = new javax.swing.JMenuItem();
        Ser = new javax.swing.JMenuItem();
        mon = new javax.swing.JMenuItem();
        Impre = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        FAC = new javax.swing.JMenuItem();
        Descrip = new javax.swing.JMenu();
        Infor = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JARED\\Downloads\\empre.jpg")); // NOI18N

        jMenu1.setText("Principal ");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Personal ");

        EM.setText("Empleados");
        EM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMActionPerformed(evt);
            }
        });
        jMenu2.add(EM);

        jMenuBar1.add(jMenu2);

        Producto.setText("Producto ");
        Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductoActionPerformed(evt);
            }
        });

        Lap.setText("Laptops");
        Lap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LapActionPerformed(evt);
            }
        });
        Producto.add(Lap);

        Des.setText("Destokp");
        Des.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DesActionPerformed(evt);
            }
        });
        Producto.add(Des);

        Ser.setText("Servidores");
        Ser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SerActionPerformed(evt);
            }
        });
        Producto.add(Ser);

        mon.setText("monitores");
        mon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monActionPerformed(evt);
            }
        });
        Producto.add(mon);

        Impre.setText("Impresoras");
        Impre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImpreActionPerformed(evt);
            }
        });
        Producto.add(Impre);

        jMenuBar1.add(Producto);

        jMenu3.setText("Compras");

        FAC.setText("Facturacion");
        FAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FACActionPerformed(evt);
            }
        });
        jMenu3.add(FAC);

        jMenuBar1.add(jMenu3);

        Descrip.setText("descripcion ");
        Descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescripActionPerformed(evt);
            }
        });

        Infor.setText("Informacion de la empresa ");
        Infor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InforActionPerformed(evt);
            }
        });
        Descrip.add(Infor);

        jMenuBar1.add(Descrip);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMActionPerformed
        EM tabla1;
        tabla1 = new EM();
        tabla1.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_EMActionPerformed

    private void DesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DesActionPerformed
         Destokp tabla3= new Destokp();
        tabla3.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_DesActionPerformed

    private void LapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LapActionPerformed
        Laptops tabla2= new Laptops ();
        tabla2.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_LapActionPerformed

    private void SerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SerActionPerformed
        Servidores tabla4= new Servidores ();
        tabla4.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_SerActionPerformed

    private void monActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monActionPerformed
        Monitor tabla5= new Monitor();
        tabla5.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_monActionPerformed

    private void ImpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImpreActionPerformed
        Impresoras tabla6= new Impresoras();
        tabla6.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_ImpreActionPerformed

    private void DescripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescripActionPerformed
        
    }//GEN-LAST:event_DescripActionPerformed

    private void InforActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InforActionPerformed
        Informacion tabla8= new Informacion ();
        tabla8.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_InforActionPerformed

    private void ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProductoActionPerformed

    private void FACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FACActionPerformed
         Factura tabla10= new Factura  ();
        tabla10.setVisible(true); 
        this.setVisible(false);
    }//GEN-LAST:event_FACActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Des;
    private javax.swing.JMenu Descrip;
    private javax.swing.JMenuItem EM;
    private javax.swing.JMenuItem FAC;
    private javax.swing.JMenuItem Impre;
    private javax.swing.JMenuItem Infor;
    private javax.swing.JMenuItem Lap;
    private javax.swing.JMenu Producto;
    private javax.swing.JMenuItem Ser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mon;
    // End of variables declaration//GEN-END:variables
}
