/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package areaJefeDesarrollo;

import Login.Login;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lalo
 */
public class jefeDesarrollo extends javax.swing.JFrame {

    /**
     * Creates new form Inicip
     */
    public jefeDesarrollo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        Aprobados = new javax.swing.JMenuItem();
        Rechazados = new javax.swing.JMenuItem();
        Recibidos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        Listadoprogramadores = new javax.swing.JMenuItem();
        Testers = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Buzon de Proyectos");

        Aprobados.setMnemonic('o');
        Aprobados.setText("Aprobados");
        Aprobados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AprobadosActionPerformed(evt);
            }
        });
        fileMenu.add(Aprobados);

        Rechazados.setMnemonic('s');
        Rechazados.setText("Rechazados");
        Rechazados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechazadosActionPerformed(evt);
            }
        });
        fileMenu.add(Rechazados);

        Recibidos.setMnemonic('a');
        Recibidos.setText("Recibidos");
        Recibidos.setToolTipText("");
        Recibidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecibidosActionPerformed(evt);
            }
        });
        fileMenu.add(Recibidos);

        jMenuItem2.setText("Cerrar Sesion");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem2);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Programadores");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        Listadoprogramadores.setMnemonic('t');
        Listadoprogramadores.setText("Listado");
        Listadoprogramadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListadoprogramadoresActionPerformed(evt);
            }
        });
        editMenu.add(Listadoprogramadores);

        menuBar.add(editMenu);

        Testers.setMnemonic('h');
        Testers.setText("Tester");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Listado");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        Testers.add(contentMenuItem);

        menuBar.add(Testers);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AprobadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AprobadosActionPerformed
        try {
            // Menu aprobados
            aprobados n1 = new aprobados();
            panel.add(n1);
            n1.show();
        } catch (SQLException ex) {
            Logger.getLogger(jefeDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AprobadosActionPerformed

    private void RechazadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechazadosActionPerformed
        try {
            // Menu rechazados
            rechazados n2 = new rechazados();
            panel.add(n2);
            n2.show();
        } catch (SQLException ex) {
            Logger.getLogger(jefeDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RechazadosActionPerformed

    private void RecibidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecibidosActionPerformed
        // Menu recibidos
      
        recibidos n3 = new recibidos();
        panel.add(n3);
        n3.show();
    }//GEN-LAST:event_RecibidosActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
        
    }//GEN-LAST:event_editMenuActionPerformed

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        try {
            // listado testers
            listadoTester listadoT = new listadoTester();
            panel.add(listadoT);
            listadoT.show();
        } catch (SQLException ex) {
            Logger.getLogger(jefeDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void ListadoprogramadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListadoprogramadoresActionPerformed
        try {
            /// listado programadores
            listadoProgramadores listadoP = new listadoProgramadores();
            panel.add(listadoP);
            listadoP.show();
        } catch (SQLException ex) {
            Logger.getLogger(jefeDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ListadoprogramadoresActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Login p = new Login();
        p.setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jefeDesarrollo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jefeDesarrollo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Aprobados;
    private javax.swing.JMenuItem Listadoprogramadores;
    private javax.swing.JMenuItem Rechazados;
    private javax.swing.JMenuItem Recibidos;
    private javax.swing.JMenu Testers;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JDesktopPane panel;
    // End of variables declaration//GEN-END:variables

}
