/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package administrador;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author oscar
 */
public class gDesarrollo extends javax.swing.JInternalFrame {

    DefaultTableModel model;
 
    
      public void actualizarTabla() throws SQLException {
       
          btnEliminar.setEnabled(true);
        btnLimpiar.setEnabled(false);
        btnActualizar.setEnabled(false);
        

        model = new DefaultTableModel();

        model.addColumn("Id_JefeD");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        model.addColumn("Edad");
        model.addColumn("Correo");
        model.addColumn("Listado_Empleados");
        
        String codigo = "", nombre = "", apellido= "", edad = "", correo= "", Listado_Empleados= "" ;
         conexionA con = new conexionA();
        String sql = "SELECT * FROM jefe_desarrollo";
        ResultSet rs;
        con.setRs(sql);
        rs = con.getRs();
        
       
        while (rs.next()) {
            codigo = rs.getString("Id_JefeD");
            nombre = rs.getString("Nombre");
            apellido = rs.getString("Apellido");
            edad = rs.getString("Edad");
            correo = rs.getString("Correo");
            Listado_Empleados = rs.getString("Listado_Empleados");
            
            model.addRow(new Object[]{codigo, nombre, apellido, edad, correo ,Listado_Empleados});
        }
        tableJefe.setModel(model);
        con.cerrarConexion();
        
    }
    public gDesarrollo() throws SQLException {
        initComponents();
         actualizarTabla();
       
        
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtJefe = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJefe = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtLEM = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestionar Jefe de Desarrolladores");

        jLabel1.setText("ID Jefe:");

        tableJefe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Jefes de Desarrollo", "Nombres", "Apellidos", "Edad", "Correo", "Lista Empleados"
            }
        ));
        tableJefe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJefeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableJefe);

        jLabel2.setText("Apellido:");

        jLabel3.setText("Nombre:");

        btnEliminar.setText("Eliminar Relacion");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel4.setText("Edad:");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel5.setText("Correo:");

        btnActualizar.setText("Actualizar");
        btnActualizar.setPreferredSize(new java.awt.Dimension(85, 23));
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        jLabel8.setText("Lista empleados");

        btnAgregar.setText("Agregar ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtJefe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(183, 183, 183))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(202, Short.MAX_VALUE)
                        .addComponent(btnAgregar)
                        .addGap(80, 80, 80)
                        .addComponent(btnEliminar)
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(118, 118, 118))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(38, 38, 38)
                        .addComponent(txtLEM, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(192, 192, 192))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txtLEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtJefe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    private void tableJefeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJefeMouseClicked
        // TODO add your handling code here:
        btnEliminar.setEnabled(true);
        btnActualizar.setEnabled(true);
        btnLimpiar.setEnabled(true);
        int fila = tableJefe.getSelectedRow();
        if ((fila > -1)) {
            txtJefe.setText(model.getValueAt(fila, 0).toString());
            txtNombre.setText(model.getValueAt(fila, 1).toString());
            txtApellido.setText(model.getValueAt(fila, 2).toString());
            txtEdad.setText(model.getValueAt(fila, 3).toString());
            txtCorreo.setText(model.getValueAt(fila, 4).toString());
            txtLEM.setText(model.getValueAt(fila, 5).toString());
           
        }

    }//GEN-LAST:event_tableJefeMouseClicked

    private void limpiarText() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtCorreo.setText("");
        txtEdad.setText("");
        txtJefe.setText("");
        txtLEM.setText("");
    }


    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        
        
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:6666/pooo", "root", "12345");
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        int fila = tableJefe.getSelectedRow();
        String Id_JefeD = model.getValueAt(fila, 0).toString();
        String Nombre = txtNombre.getText();
        String Apellido = txtApellido.getText();
        int Edad = Integer.parseInt(txtEdad.getText()) ;
        String Correo =txtCorreo.getText(); 
        int Listado_Empleados = Integer.parseInt( txtLEM.getText());
        
        PreparedStatement stmt = null;
        try {
            stmt = con.prepareStatement("UPDATE Jefe_Desarrollo SET Nombre=?, Apellido=?, Edad=?, Correo=?, "
                    + " Listado_Empleados=? WHERE Id_JefeD="+Id_JefeD);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setString(
                    1, Nombre);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setString(
                    2, Apellido);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setInt(
                    3, Edad);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setString(
                    4, Correo);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
        try {
            stmt.setInt(
                    5, Listado_Empleados);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            int i = stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "El Jefe de Desarrollo fue actualizado con exito.");
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }

          try {
            actualizarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed


    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          conexionA con = null;
        try {
            con = new conexionA();
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        int fila = tableJefe.getSelectedRow();
        String codigo = model.getValueAt(fila, 0).toString();
        String sql = "DELETE FROM Jefe_Desarrollo WHERE Id_JefeD=" + codigo;
        try {
            con.setQuery(sql);
            JOptionPane.showMessageDialog(null, "El Jefe de Desarrollo fue borrado con exito.");
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.cerrarConexion();
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
       
                  try {
            actualizarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        
        
        
        
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarText();

    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
          try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        Connection con = null;
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:6666/pooo", "root", "12345");
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        String Id_JefeD = txtJefe.getText();
        String Nombre = txtNombre.getText();
        String Apellido = txtApellido.getText();
        int Edad = Integer.parseInt(txtEdad.getText() ) ;
        String Correo =txtCorreo.getText();
        int Listado_Empleados = Integer.parseInt( txtLEM.getText());
        PreparedStatement stmt = null;
        try {
            stmt = con.prepareStatement("INSERT INTO Jefe_Desarrollo(Id_JefeD,Nombre, Apellido, Edad, Correo, Listado_Empleados) VALUES(?,?,?,?,?,?)");
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setString(
                    1, Id_JefeD);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setString(
                    2, Nombre);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setString(
                    3, Apellido);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            stmt.setInt(
                    4, Edad);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            stmt.setString(
                    5, Correo);
        } catch (SQLException ex) {
        
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try {
            stmt.setInt(
                    6, Listado_Empleados);
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            int i = stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "El Jefe de Desarrollo fue registrado con exito.");
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
 try {
            actualizarTabla();
        } catch (SQLException ex) {
            Logger.getLogger(gDesarrollo.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJefe;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtJefe;
    private javax.swing.JTextField txtLEM;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
